question_data = [
    {"question": "A slug's blood is green.", "correct_answer": "True"},
    {"question": "The loudest animal is the African Elephant.", "correct_answer": "False"},
    {"question": "Approximately one quarter of human bones are in the feet.", "correct_answer": "True"},
    {"question": "The total surface area of a human lungs is the size of a football pitch.", "correct_answer": "True"},
    {"question": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "correct_answer": "True"},
    {"question": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "correct_answer": "False"},
    {"question": "It is illegal to pee in the Ocean in Portugal.", "correct_answer": "True"},
    {"question": "You can lead a cow down stairs but not up stairs.", "correct_answer": "False"},
    {"question": "Google was originally called 'Backrub'.", "correct_answer": "True"},
    {"question": "Buzz Aldrin's mother's maiden name was 'Moon'.", "correct_answer": "True"},
    {"question": "No piece of square dry paper can be folded in half more than 7 times.", "correct_answer": "False"},
    {"question": "A few ounces of chocolate can to kill a small dog.", "correct_answer": "True"},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"hard","question":"In &quot;The Sims&quot; series, the most members in a household you can have is 8.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"DragonForce&#039;s &#039;Through the Fire and Flames&#039; is widely considered to be the hardest song in the Guitar Hero series.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"Gordon Freeman, the protagonist of &quot;Half-Life&quot;, is said to have once had a ponytail.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"In &quot;Super Mario World&quot;, the rhino mini-boss, Reznor, is named after the lead singer of the band &quot;Nine Inch Nails&quot;.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"The character that would eventually become Dr. Eggman was considered for the role of Sega&#039;s new flagship mascot before Sonic was.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"Hidden in the files for &quot;Mario Kart Arcade GP&quot; is a picture of the Beslan school hostage crisis.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"The scrapped Sonic the Hedgehog 2 level &quot;Hidden Palace Zone&quot; was later reused in the iOS port of the game. ","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"There are 2 player roles in Trouble in Terrorist Town.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"Doki Doki Literature Club was developed in Japan.","correct_answer":"False","incorrect_answers":["True"]}
]
